### ISSUE TITLE
Spinner showing on account status

### ISSUE THREAD

**Issue by carletex** [BuidlGuidl/batch0.buidlguidl.com#22]
When showing the account info an infinite spinner shows when you don't have your wallet connected.

It shouldn't show anything... and just load the spinner/info when you connect your wallet.

![image](https://github.com/BuidlGuidl/batch0.buidlguidl.com/assets/2486142/b6c85049-8f63-488e-a657-32d15113e4ae)

For more info: This is the PR https://github.com/BuidlGuidl/batch0.buidlguidl.com/pull/16/ that implemented showing the account info.

**Comment by miralsuthar** [comment]
Can I take this, I know where the bug is

**Comment by iafhurtado** [comment]
Wow, that was quick, I'll look into it as well but get it done @miralsuthar 🎯
