### ISSUE TITLE
List the members of the batch (read OnbardingBatch contract)

### ISSUE THREAD

**Issue by edakturk14** [BuidlGuidl/batch0.buidlguidl.com#3]
## Goal

Show the current members of your batch in the app.

- Show it on the main page or create a page (/builders) listing all the builders registered in the BatchRegistry contract (see #2)
- Each builder should link to their personal profile (see #1)

**Comment by solo1g** [comment]
I'll take this one.

**Comment by carletex** [comment]
Assigned! Thanks
