### ISSUE TITLE
Change the Logo / title / subtitle

### ISSUE THREAD

**Issue by edakturk14** [BuidlGuidl/batch0.buidlguidl.com#7]
## Goal

Update your batch's mainpage. 

![image](https://github.com/BuidlGuidl/batch-template/assets/2486142/52a77020-0c08-4136-8cc5-244bc3bd088a)

- Create a random logo (or use Dall-E!) to generate a batch logo
- title: Batch #{batch_number}
- subtitle: Whatever you feel appropriate :)

**Comment by YanVictorSN** [comment]
Hello @carletex. Can you assign me to work on this issue, please?

**Comment by carletex** [comment]
Done! Thanks for taking it

**Comment by ZakGriffith** [comment]
Completed in #15
